[package]
name = "recsplit"
authors = ["Jonatan Ziegler"]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "RecSplit minimal perfect hash function"
repository = "https://github.com/worldofjoni/RecSplit"
keywords = ["hashing", "mphf", "perfect-hash", "perfect"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
bitvec = "1.0.1"
env_logger = "0.11.3"
log = "0.4.21"
static_assertions = "1.1.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
gnuplot = "0.0.43"
rand = "0.8.5"

[features]
debug_output = []


[[bench]]
name = "rec_bench"
harness = false

[[bench]]
name = "mvp_bench"
harness = false

[[bench]]
name = "micro"
harness = false

# [[bin]]
# name = "testbin"
# path = "src/bin.rs"

[profile.release]
debug = true # for flamegraph
lto = "thin"
