[package]
name = "recsplit"
authors = ["Jonatan Ziegler"]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "RecSplit minimal perfect hash function"
repository = "https://github.com/worldofjoni/RecSplit"
keywords = ["hashing", "mphf", "perfect-hash", "perfect"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = { versuion = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"

[[bench]]
name = "search_hash"
harness = false

[dependencies]
ahash = "0.8.11"
env_logger = "0.11.3"
fnv = "1.0.7"
log = "0.4.21"
rustc-hash = "1.1.0"


[profile.release]
debug = true # for flamegraph
lto = true
